<?php
$block = $this->getLayout()->createBlock(
    'Anees\Training\Block\Post\Lists'
);
?>
<table style="width: 50%">
    <thead>
    <tr>
        <th>Sr. No</th>
        <th>Title</th>
        <th>Content</th>

    </tr>
    </thead>
    <tbody>
    <?php foreach ($block->getcoll() as $post): ?>
        <tr>
            <td><?= /* @escapeNotVerified */ $post->getentity_id() ?></td>
            <td><?= /* @escapeNotVerified */ $post->getTitle() ?></td>
            <td><?= /* @escapeNotVerified */ $post->getContent() ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
