<?php
$block = $this->getLayout()->createBlock(
    'Anees\Training\Block\Post\Lists'
);
?>
<table style="width: 100%">
    <thead>
    <tr>
        <th>Sr. No</th>
        <th>Title</th>
        <th>Content</th>
        <th>Actions</th>

    </tr>
    </thead>
    <tbody>
    <?php foreach ($block->getcoll() as $post): ?>
        <tr>
            <td><?= /* @escapeNotVerified */ $post->getentity_id() ?></td>
            <td><?= /* @escapeNotVerified */ $post->getTitle() ?></td>
            <td><?= /* @escapeNotVerified */ $post->getContent() ?></td>
            <td>
                <a href="<?= $block->escapeUrl($block->getUrl('training/post/edit', ['id'=>$block->escapeHtml($post->getentity_id())]))?>">Edit</a>
                |
                <a href="<?= $block->escapeUrl($block->getUrl('training/post/delete', ['id'=>$block->escapeHtml($post->getentity_id())]))?>">Delete</a>

            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<br/><br/>
<?php  if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom">
        <?php echo $block->getPagerHtml(); ?>
    </div>
<?php endif; ?>
